require "luca.keymaps"
require "luca.plugins"
require "luca.cmp"
require "luca.lsp"
require "luca.fidget"
require "luca.telescope"
require "luca.treesitter"
require "luca.options"
require "luca.base16"
require "luca.toggleterm"
require "luca.nvim-autopairs"

vim.cmd "colo kanagawa"
vim.cmd "hi! link Conceal texMathGroup"
