require "luca.keymaps"
require "luca.plugins"
require "luca.cmp"
require "luca.lsp"
require "luca.fidget"
require "luca.telescope"
require "luca.treesitter"
require "luca.options"
require "luca.base16"
require "luca.toggleterm"
require "luca.nvim-commenter"
require "luca.vimtex"
require "luca.nvim-r"

vim.cmd([[colo melange]])
vim.g.vscode_style = "dark"
vim.cmd "hi! link Conceal texMathGroup"
